version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  llm-app:
    build: ./llm
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  llm-api:
    build: ./llm_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: